### ISSUE TITLE
Issue when there is a `.` in the path to a view

### ISSUE THREAD

**Issue by chood531** [codemyviews/vanilla-core#1]
There is an issue when there is a `.` in the path to the view folder.  For example:

```
/home/deploycmv/mayven-20.autodeploy/wp-content/themes/mayven
```

This gets re-written to:

```
/home/deploycmv/mayven-20/autodeploy/wp-content/themes/mayven
```

I tracked this down to this file:

```
wp-content/themes/mayven/vendor/codemyviews/vanilla-core/Concerns/IntegratesBlade.php
```

Specifically the `overrideTemplate()` method, this line `$template = str_replace('.', '/', $this->decideTemplate()) . '.blade.php';`

Can we please apply a fix for this?

**Comment by ikoolik** [comment]
This one was fixed in [v1.3.2](https://github.com/codemyviews/vanilla-core/releases/tag/v1.3.2)
Sorry for not replying here.
