### ISSUE TITLE
Version number getting added to the theme.css file path

### ISSUE THREAD

**Issue by chood531** [codemyviews/vanilla-core#2]
It looks like we have a version number getting added to the `theme.css` path: https://d.pr/i/zjtyRW

I think this is not needed since we are using `mix` for versioning of static assets (this seems to be working fine on `app.js`, for example.

**Comment by ikoolik** [comment]
Fix in master. Going to be part of v1.3.6

**Comment by ikoolik** [comment]
v1.3.6 shipped
